# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ab82f122718af01befbc08e3e96cc8c1"
name = "Cracktab - AI SEO and Blog"
handle = "seo-booster-ai"
application_url = "https://urchin-app-p3gwr.ondigitalocean.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_content,write_content,read_themes,write_themes,read_metaobjects,write_metaobjects,read_files,write_files"

[auth]
redirect_urls = [
  "https://urchin-app-p3gwr.ondigitalocean.app/auth/callback",
  "https://urchin-app-p3gwr.ondigitalocean.app/auth/shopify/callback",
  "https://urchin-app-p3gwr.ondigitalocean.app/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = ""
